title: Vineet Juneja
description: Buseinss Transformation and Strategy & Data Scicene enthusiast
logo: /assets/img/logo.png
  <a href="https://www.linkedin.com/in/vineetjuneja/">LinkedIn</a> |
  <a href="https://github.com/coolblueice/">GitHub</a>
  Bringing over 23 years of experience in creating value for Clients, building large teams and organizations that are built to last.
I truly believe that the unique value we provide to our clients, employees and society comes from authenticity and simplicity.
<br>
Business Executive and a Data Science entusiast!

theme: jekyll-theme-architect
