title: <p align="center"> Vineet Juneja </p>
logo: /assets/img/logo.png
description: 
<p align="center">
<a href="https://www.linkedin.com/in/vineetjuneja/"> Linkedin </a>

Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
